# Copyright (C) 2026 Bemade Inc.
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
"""Token storage for the mail gateway endpoint.

Tokens are **never** persisted in clear text — only the sha256 hex digest
is stored. The raw token is generated by :meth:`action_generate` and
returned to the caller exactly once (the wizard then displays it once).

Verification :meth:`validate_token` runs a constant-time comparison over
the full set of active tokens so timing cannot reveal whether any
candidate matched (the absence of an early ``break`` is intentional).
"""

import hashlib
import hmac
import logging
import secrets
from typing import Optional

from odoo import _, api, fields, models
from odoo.exceptions import ValidationError

_logger = logging.getLogger(__name__)

# 256 bits of entropy. token_urlsafe(n) yields ceil(n * 4/3) chars; 32
# bytes → 43 chars.
_TOKEN_BYTES = 32
_HASH_LEN = 64  # sha256 hex digest length


class BemadeMailGatewayToken(models.Model):
    _name = "bemade.mail_gateway.token"
    _description = "Bemade Mail Gateway Token"
    _order = "active desc, create_date desc"

    name = fields.Char(
        required=True,
        index=True,
        help="Human-readable label for this token (e.g. 'omg-sugar', 'omg-pneumac').",
    )
    description = fields.Text(
        help="Free-form notes — what integration uses this token, who owns it, etc.",
    )
    token_hash = fields.Char(
        size=_HASH_LEN,
        required=True,
        readonly=True,
        index=True,
        help="sha256 hex digest of the secret. The raw token is shown once at "
        "creation and never persisted in clear.",
    )
    active = fields.Boolean(
        default=True,
        help="Uncheck to disable without deleting (preserves audit trail).",
    )
    expires_at = fields.Datetime(
        help="Optional hard expiry. Tokens past this date validate as invalid.",
    )
    last_used_at = fields.Datetime(
        readonly=True,
        help="Timestamp of the most recent successful validation.",
    )
    last_used_ip = fields.Char(
        size=45,  # enough for an IPv6 address
        readonly=True,
        help="Source IP of the most recent successful validation.",
    )
    use_count = fields.Integer(
        readonly=True,
        default=0,
        help="Number of times this token has been validated successfully.",
    )
    allowed_ips = fields.Char(
        help="Comma-separated CIDR list. Empty = no IP restriction. "
        "(Enforced in V2; field present for forward compatibility.)",
    )

    _sql_constraints = [
        ("name_unique", "unique(name)", "A mail-gateway token with this label already exists."),
        (
            "token_hash_unique",
            "unique(token_hash)",
            "Token hash collision (this is essentially impossible — please retry).",
        ),
    ]

    # ---- Public API --------------------------------------------------------

    @api.model
    def action_generate(
        self,
        name: str,
        description: str = "",
        expires_at: fields.Datetime | None = None,
    ) -> tuple["BemadeMailGatewayToken", str]:
        """Generate a new token record and return ``(record, raw_token)``.

        The ``raw_token`` is shown to the operator exactly once via the
        creation wizard, then forgotten — it is never re-derivable from
        the stored hash.

        :raises ValidationError: if ``name`` is empty or already taken.
        """
        self.check_access_rights('create')
        if not name or not name.strip():
            raise ValidationError(_("A label is required."))

        raw = secrets.token_urlsafe(_TOKEN_BYTES)
        token_hash = hashlib.sha256(raw.encode("ascii")).hexdigest()
        rec = self.sudo().create(
            {
                "name": name.strip(),
                "description": description or "",
                "token_hash": token_hash,
                "expires_at": expires_at,
            }
        )
        # Deliberately not logging the raw token — security baseline.
        _logger.info("mail_gateway_token_generated label=%s id=%d", rec.name, rec.id)
        return rec, raw

    @api.model
    def validate_token(self, raw_token: str, ip: str = "") -> Optional["BemadeMailGatewayToken"]:
        """Look up a token by raw value, in constant time over active tokens.

        Returns the matching record (single-record recordset) on success,
        or an empty recordset on failure. On success, also updates the
        ``last_used_*`` fields on the record.

        Constant-time guarantees:

        * We hash the input *before* any DB lookup.
        * We iterate the **full** set of active candidates and call
          :func:`hmac.compare_digest` on every one — there is no early
          break. A timing attacker cannot tell from response time whether
          a candidate matched (the only timing leak is the post-match
          DB write, which only reveals "some token matched", a fact the
          attacker already learns from the HTTP status code).
        """
        self.check_access_rights('read')
        if not raw_token:
            return self.browse()

        h = hashlib.sha256(raw_token.encode("ascii")).hexdigest()
        candidates = self.sudo().search([("active", "=", True)])

        matched = self.browse()
        for tok in candidates:
            if hmac.compare_digest(tok.token_hash, h):
                matched = tok
            # No `break` — keep iterating for constant-time behaviour.

        if not matched:
            return matched

        if matched.expires_at and matched.expires_at < fields.Datetime.now():
            return self.browse()

        matched.sudo().write(
            {
                "last_used_at": fields.Datetime.now(),
                "last_used_ip": (ip or "")[:45],
                "use_count": matched.use_count + 1,
            }
        )
        return matched

    def action_revoke(self) -> bool:
        """Disable the token without deleting (preserves audit trail)."""
        for rec in self:
            rec.active = False
            _logger.info("mail_gateway_token_revoked label=%s id=%d", rec.name, rec.id)
        return True
