def _backfill_supply_sale_line(env):
    """Backfill the core ``sale_line_id`` link on in-flight supply RFQ lines.

    A supply RFQ line only becomes adoptable by the procurement engine once its
    core ``sale_line_id`` points at the SO line it covers. Lines generated by an
    older monolith (or created before this module was installed) may only carry
    ``supply_so_line_id``. Copying it across lets orders that are already in
    flight benefit from the adoption fix without being re-created.

    Runs once on install (``post_init_hook``); a no-op on a database with no
    supply RFQ lines.
    """
    env.cr.execute(
        """
        UPDATE purchase_order_line pol
        SET sale_line_id = pol.supply_so_line_id
        FROM purchase_order po
        WHERE pol.order_id = po.id
          AND pol.supply_so_line_id IS NOT NULL
          AND pol.sale_line_id IS NULL
          AND po.state IN ('draft', 'sent', 'purchase')
        """
    )
