from . import mail_followers
from . import patient
from . import patient_injury
from . import patient_contact
from . import res_partner
from . import res_users
from . import sports_team
from . import treatment_note
from . import injury_document
from . import sports_event
from . import base_partner_merge
from . import team_role_mass_assign_wizard
from . import sports_event_timesheet
from . import res_config_settings
from . import event_invoicing_wizard
from . import event_vendor_po_wizard
from . import event_recurrence_wizard
from . import event_batch_invoicing_wizard
from . import sale_order_line
from . import event_cancel_wizard
