from . import data_recycle_model
from . import data_recycle_record
from . import mail_followers
from . import mail_activity
from . import patient
from . import patient_injury
from . import injury_note_history
from . import patient_contact
from . import res_partner
from . import res_users
from . import sports_team
from . import sports_organization_staff
from . import team_org_staff_promote_wizard
from . import sports_team_user_rank
from . import sports_team_note_history
from . import sports_team_digest
from . import treatment_note
from . import sports_quick_note
from . import injury_document
from . import sports_event
from . import sports_clinic_attendance
from . import base_partner_merge
from . import team_role_mass_assign_wizard
from . import team_player_removal_wizard
from . import sports_event_timesheet
from . import res_config_settings
from . import event_invoicing_wizard
from . import event_vendor_po_wizard
from . import event_recurrence_wizard
from . import event_batch_invoicing_wizard
from . import sale_order_line
from . import event_cancel_wizard
from . import patient_merge_wizard
