from . import mail_followers
from . import patient
from . import patient_injury
from . import patient_contact
from . import res_partner
from . import res_users
from . import sports_team
from . import treatment_note
from . import injury_document
from . import project_task
from . import project_task_security_test
from . import project_project
from . import sports_event
from . import base_partner_merge
from . import team_role_mass_assign_wizard
