# Copyright 2026 Bemade Inc.
# License LGPL-3 - See https://www.gnu.org/licenses/lgpl-3.0.html

import logging
from datetime import timedelta

from odoo import Command, _, api, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)

MAX_PRICE_AGE_PARAM = "mrp_bom_variant_rule.max_price_age_days"
DEFAULT_MAX_PRICE_AGE_DAYS = 365


class MrpBom(models.Model):
    _inherit = "mrp.bom"

    generated_rule_set_id = fields.Many2one(
        comodel_name="mrp.bom.rule.set",
        string="Generated From Ruleset",
        readonly=True,
        copy=False,
        index=True,
        help="Set when this bill of materials was produced by the rule "
        "engine. A hand-built bill of materials never carries a ruleset, and "
        "is never overwritten by generation.",
    )
    generated_predecessor_id = fields.Many2one(
        comodel_name="mrp.bom",
        string="Supersedes",
        readonly=True,
        copy=False,
        index=True,
        help="The generated bill of materials this one replaced. A bill of "
        "materials a manufacturing order has already consumed is superseded "
        "rather than rewritten, so what was actually built stays readable.",
    )
    generated_fingerprint = fields.Char(
        string="Input Fingerprint",
        readonly=True,
        copy=False,
        index=True,
        help="Digest of the ruleset revision, the variant's attribute values "
        "and the parameter values consumed when this bill of materials was "
        "generated. A hand-built bill of materials never carries one.",
    )

    def _bom_rule_line_signature(self):
        """What this bill of materials currently says, comparably."""
        self.ensure_one()
        return sorted(
            (
                line.product_id.id,
                round(line.product_qty, 6),
                line.product_uom_id.id,
            )
            for line in self.bom_line_ids
        )

    def _bom_rule_stale_state(self):
        """Classify this bill of materials against the rules as they stand.

        Returns ``(state, reason)`` where state is ``current``, ``stale`` or
        ``refused``.

        Staleness is decided by asking what regeneration would produce now,
        not by comparing revisions. The revision moves whenever any rule in
        the table is touched, and most edits are irrelevant to most variants;
        reporting on the revision alone would bury the handful of bills of
        materials that genuinely changed under everything that did not.
        """
        self.ensure_one()
        rule_set = self.generated_rule_set_id
        product = self.product_id
        if not rule_set or not product:
            return "current", ""
        try:
            resolved = product._bom_rule_resolve_lines(rule_set)
        except UserError as err:
            return "refused", str(err)
        expected = sorted(
            (component.id, round(qty, 6), uom.id)
            for _rule, component, qty, uom in resolved
        )
        if expected != self._bom_rule_line_signature():
            return "stale", _(
                "The rules now produce different components or quantities "
                "for %(product)s.",
                product=product.display_name,
            )
        return "current", ""

    @api.model
    def _bom_rule_stale_report(self):
        """Survey every generated bill of materials against its ruleset.

        Reports only. The two buckets are kept apart because they need
        different responses: a stale bill of materials is regenerated by
        whoever owns the quotation, whereas one that would now be refused is a
        defect in the rule table that no amount of regenerating will fix.
        """
        boms = self.search([("generated_rule_set_id", "!=", False)])
        stale = self.browse()
        refused = self.browse()
        reasons = {}
        for bom in boms:
            state, reason = bom._bom_rule_stale_state()
            if state == "stale":
                stale |= bom
            elif state == "refused":
                refused |= bom
            else:
                continue
            reasons[bom.id] = reason
        return {"stale": stale, "refused": refused, "reasons": reasons}

    @api.model
    def _cron_report_stale_boms(self):
        """Scheduled action behind the stale-BOM report.

        It writes nothing. A cron that quietly regenerated a bill of materials
        would change what an open quotation was costed from, days after the
        number was given to a customer.
        """
        report = self._bom_rule_stale_report()
        if report["stale"]:
            _logger.warning(
                "%d generated bill(s) of materials are out of step with "
                "their ruleset and can be regenerated: %s",
                len(report["stale"]),
                ", ".join(report["stale"].mapped("display_name")),
            )
        if report["refused"]:
            _logger.warning(
                "%d generated bill(s) of materials could no longer be "
                "generated at all and need a rule author: %s",
                len(report["refused"]),
                ", ".join(report["refused"].mapped("display_name")),
            )
        return report

    cost_confidence = fields.Selection(
        selection=[
            ("firm", "Firm"),
            ("estimated", "Estimated"),
            ("no_components", "No components"),
        ],
        string="Cost Basis",
        readonly=True,
        copy=False,
        help="How far the cost of this bill of materials can be relied on.\n\n"
        "Firm: every component had a vendor price no older than the maximum "
        "price age when this bill of materials was generated.\n"
        "Estimated: at least one component had no vendor price, or only a "
        "stale one. The components responsible are listed alongside, and are "
        "the ones worth requoting.\n"
        "No components: there is nothing to judge.\n\n"
        "This never blocks anything and never changes a price. It reports how "
        "old the numbers underneath a cost are, so that an estimate is not "
        "mistaken for a firm figure.",
    )
    cost_unpriced_product_ids = fields.Many2many(
        comodel_name="product.product",
        relation="mrp_bom_cost_unpriced_product_rel",
        column1="bom_id",
        column2="product_id",
        string="Components Without a Vendor Price",
        readonly=True,
        copy=False,
    )
    cost_stale_priced_product_ids = fields.Many2many(
        comodel_name="product.product",
        relation="mrp_bom_cost_stale_priced_product_rel",
        column1="bom_id",
        column2="product_id",
        string="Components With an Outdated Vendor Price",
        readonly=True,
        copy=False,
    )

    @api.model
    def _bom_rule_max_price_age_days(self):
        """How old a vendor price may be before it stops counting as current.

        Deliberately configuration: a year is defensible for fabricated
        vessels and absurd for commodity resin, and only the people running
        the business know which they are buying.
        """
        raw = (
            self.env["ir.config_parameter"]
            .sudo()
            .get_param(MAX_PRICE_AGE_PARAM)
        )
        try:
            days = int(raw)
        except (TypeError, ValueError):
            return DEFAULT_MAX_PRICE_AGE_DAYS
        return days if days > 0 else DEFAULT_MAX_PRICE_AGE_DAYS

    @api.model
    def _bom_rule_price_state(self, product, cutoff):
        """Classify one component as ``priced``, ``stale`` or ``unpriced``.

        A single current quote settles it, whichever vendor it came from. The
        preferred vendor decides who gets the purchase order; it has no
        bearing on whether a number exists to cost the quotation with.
        """
        sellers = product.seller_ids
        if not sellers:
            return "unpriced"
        for seller in sellers:
            quoted_on = seller.date_start
            if not quoted_on and seller.write_date:
                # No explicit start date, so the last time anyone touched the
                # record is the best evidence of when the price was agreed.
                quoted_on = seller.write_date.date()
            if not quoted_on or quoted_on >= cutoff:
                return "priced"
        return "stale"

    def _bom_rule_compute_cost_confidence(self):
        """Record the price coverage of this bill of materials' components.

        Called after generation, never as a gate on it: an approximate bill of
        materials is the whole point of the module, and one built on old
        prices is still worth more than the placeholder it replaces.
        """
        max_age = self._bom_rule_max_price_age_days()
        cutoff = fields.Date.today() - timedelta(days=max_age)
        for bom in self:
            components = bom.bom_line_ids.product_id
            unpriced = self.env["product.product"]
            stale = self.env["product.product"]
            for component in components:
                state = self._bom_rule_price_state(component, cutoff)
                if state == "unpriced":
                    unpriced |= component
                elif state == "stale":
                    stale |= component
            if not components:
                confidence = "no_components"
            elif unpriced or stale:
                confidence = "estimated"
            else:
                confidence = "firm"
            bom.write(
                {
                    "cost_confidence": confidence,
                    "cost_unpriced_product_ids": [
                        Command.set(unpriced.ids)
                    ],
                    "cost_stale_priced_product_ids": [
                        Command.set(stale.ids)
                    ],
                }
            )
        return True
