from . import test_cat_01_domain
from . import test_cat_02_competency
from . import test_cat_03_prerequisite
from . import test_cat_04_criteria
from . import test_cat_05_questions
from . import test_cat_06_units
from . import test_cat_07_protocol_policy
from . import test_cat_09_publication
from . import test_cat_10_import
from . import test_cat_11_fiche_full
from . import test_cat_12_procedure
from . import test_cat_13_job_aid
from . import test_cat_14_demo_notes
from . import test_cat_15_icons
from . import test_cat_16_authoring
from . import test_cat_17_whole_document_bodies
from . import test_std_01_standard
from . import test_std_02_qualification
from . import test_std_03_tieback
from . import test_std_04_subqual
from . import test_std_05_job_requirement
from . import test_evl_01_session
from . import test_evl_02_evaluator_constraints
from . import test_evl_03_04_parts
from . import test_evl_05_decision
from . import test_evl_06_reprise
from . import test_evl_07_signature_lock
from . import test_evl_08_evidence_retention
from . import test_evl_09_10_certification
from . import test_val_01_expiry
from . import test_rpt_01_grid
from . import test_rpt_04_matrix
from . import test_sec_01_access
from . import test_rpt_02_job_aid
from . import test_rpt_03_fiche
from . import test_rpt_06_procedure_notes
from . import test_rpt_07_print_wizard
from . import test_cat_18_import_guard
