# -*- coding: utf-8 -*-
{
    "name": "Lost Messages Routing - UX Improvements",
    "version": "18.0.1.1.0",
    "category": "Discuss",
    "summary": "Subcategories, batch actions and triage wizards for lost messages",
    "author": "Bemade Inc.",
    "website": "https://bemade.org",
    "license": "LGPL-3",
    "depends": [
        "mail_manual_routing",
        "mail_manual_routing_fix",
        "mail_loop_prevention",
        "mail_composer_from_selector",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/lost_message_subcategory_data.xml",
        "views/lost_message_subcategory_views.xml",
        "views/mail_message_views.xml",
        "wizards/mail_categorize_wizard_views.xml",
        "wizards/mail_invalid_address_wizard_views.xml",
        "wizards/mail_finance_triage_wizard_views.xml",
        "wizards/mail_forward_wizard_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}
