from . import test_patient
from . import test_rights
from . import test_users
from . import test_portal_access
from . import test_treatment_professional_consistency
from . import test_player_removal
from . import test_mail_activity_portal_access
from . import test_mail_activity_portal_integration
from . import test_portal_activity_default_todo
from . import test_portal_injury_autoassign_integration
from . import test_event_invoicing_wizard
from . import test_team_org_backlink
from . import test_therapist_access_revoke
from . import test_silent_therapist
from . import test_event_auto_access
from . import test_hide_injury_from_coach
from . import test_events_calendar_portal
from . import test_portal_injury_cards
from . import test_event_staff_selection
# T0 (coverage pre-pass): previously-orphaned test files now registered
from . import test_security_integration
from . import test_player_availability
from . import test_treatment_notes
from . import test_portal_integration
from . import test_injury_notifications
from . import test_portal_injury_form
from . import test_e2e_workflows
from . import test_injury_assignment
from . import test_cov_event_cancel_wizard
from . import test_cov_team_role_mass_assign_wizard
from . import test_cov_event_recurrence_wizard
from . import test_cov_event_vendor_po_wizard
from . import test_cov_base_partner_merge
from . import test_cov_sports_event_timesheet
from . import test_cov_sports_team
from . import test_cov_patient_injury
from . import test_cov_patient
from . import test_cov_team_staff_portal
from . import test_cov_events_portal
from . import test_cov_patient_injury_portal
from . import test_cov_player_management_portal
from . import test_cov_task_management_portal
from . import test_cov_team_management_portal
from . import test_cov_timesheets_portal
