# -*- coding: utf-8 -*-
from . import (
    test_uc01_curriculum_import,
    test_uc02_blocks_and_days,
    test_uc03_week_templates,
    test_uc04_block_actuals,
    test_uc05_traces,
    test_uc06_coverage,
    test_uc07_indicators_reviews,
    test_uc08_journal,
    test_uc09_material_projects,
    test_uc10_access,
    test_uc11_export,
    test_uc12_deliverables,
    test_uc13_reading,
    test_uc14_submissions,
    test_uc15_journal_api,
    test_uc16_i18n,
    test_uc17_block_journal,
    test_uc18_log_plan,
    test_uc19_close_day,
    test_uc20_block_week_filters,
)
